// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvvflbsdbnkqcmsmacbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dmZsYnNkYm5rcWNtc21hY2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NDA5OTIsImV4cCI6MjA3NjExNjk5Mn0.Q-GMZ_8vQOarYiAIMJ6dww-49NzhkOOOHoPyeT8nS6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});